swsnu/swpp2021-team10

backend/connectoon/artist/admin.py, backend/connectoon/artist/apps.py, backend/connectoon/artist/models.py, backend/connectoon/artist/tests.py, backend/connectoon/artist/views.py, backend/connectoon/review/models.py, backend/connectoon/tag/models.py, backend/connectoon/work/models.py
DB구조를 위한 model을 만들었습니다.
user는 django기본 툴 사용해서 해야할 것 같은데 아직 쓸 줄 몰라서 나중에 추가하도록 하겠습니다.
foreignkey/many-to-many와 review의 content길이를 설정을 얼마나 길게 해야할지에 대해 얘기해주면 감사하겠습니다.
artist를 추가 안해두어 추가했습니다.
=> Db structure

backend/connectoon/.gitignore, backend/connectoon/connectoon/urls.py, backend/connectoon/review/urls.py, backend/connectoon/review/views.py, backend/connectoon/tag/urls.py, backend/connectoon/tag/views.py, backend/connectoon/user/urls.py, backend/connectoon/user/views.py, backend/connectoon/work/urls.py, backend/connectoon/work/views.py
Created url & view structures of following directories.
- work
- review
- tag
- user
=> Create url & view structures

.travis.yml, README.md
=> added coverage

backend/connectoon/connectoon/urls.py, backend/connectoon/user/tests.py, backend/connectoon/user/views.py
=> Add token getter w/ tests

backend/connectoon/user/tests.py, backend/connectoon/user/views.py
Login feature과 본인 정보 가져오는 feature implement 했습니다.
=> Add Login & User me 

frontend/connectoon/src/Containers/Search/Search.test.js, frontend/connectoon/src/Containers/TagSearchWindow/TagSearchWindow.test.js
Search 테스트에 Work object 클릭하는 부분 추가했고 TagSearcgWindow 테스트파일 추가했습니다.
=> Modify Search test and Add tagSearchWindow test

backend/connectoon/work/views.py, frontend/connectoon/.eslintrc.js, frontend/connectoon/src/Containers/NavBar/NavBar.css, frontend/connectoon/src/Containers/NavBar/NavBar.js, frontend/connectoon/src/Containers/NavBar/NavBar.test.js, frontend/connectoon/src/Containers/Search/Search.js, frontend/connectoon/src/store/actions/actionTypes.js, frontend/connectoon/src/store/actions/index.js, frontend/connectoon/src/store/actions/work.js, frontend/connectoon/src/store/reducers/work.js, frontend/connectoon/src/store/reducers/work.test.js
백엔 work/views.py에서 get search works 메소드 마이너한 수정
NavBar에서 검색창을 사용해 Search 페이지로 가는 기능 구현
검색창의 입력값을 넘겨주는 메소드를 work 리듀서에 달아놨습니다.
서치 관련해서 백엔 알고리즘 수정도 아마 곧..
=> Implement NavBar -> Search transition

backend/connectoon/work/tests.py, backend/connectoon/work/views.py, frontend/connectoon/src/Containers/Search/Search.js
백엔 search용 work를 가져오는 과정에서 필터 함수를 적극 사용해 속도를 올렸습니다.
프엔 search는 저번 발표때는 고쳐서 보여줬지만 레포에는 고쳐져 있지 않던 마이너한 수정입니다.
=> Improve search speed

frontend/connectoon/src/Containers/Register/Register.js
=> Fix frontend test error

backend/connectoon/review/tests.py, backend/connectoon/review/views.py, frontend/connectoon/src/Components/BoardReview/BoardReview.js, frontend/connectoon/src/Components/BoardReview/BoardReview.test.js, frontend/connectoon/src/Containers/Board/Board.js, frontend/connectoon/src/Containers/Board/Board.test.js, frontend/connectoon/src/store/actions/review.js, frontend/connectoon/src/store/actions/review.test.js
=> Board review

backend/connectoon/review/tests.py, backend/connectoon/user/tests.py, backend/connectoon/user/views.py, backend/connectoon/work/tests.py, backend/connectoon/work/views.py
practice session에서 만들어놓은 issue 해결했습니다.
=> Fix variable start with capital letter

backend/connectoon/user/tests.py, backend/connectoon/user/views.py
유저 개인정보 수정 backend implement 했습니다.
```python
request.method = 'POST'
request._load_post_and_files()
request.method = 'PUT'
request.PUT = request.POST
```
위 코드는 https://dzone.com/articles/parsing-unsupported-requests-put-delete-etc-in-dja 를 참고했습니다.
=> Implement user data update feature

frontend/connectoon/src/Components/DetailReview/DetailReview.css, frontend/connectoon/src/Components/DetailReview/DetailReview.js, frontend/connectoon/src/Components/WriteReview/WriteReview.css
WorkDetail에서 more 버튼 눌러서 글 더 보이게 만드는 기능 삭제하고 대신 5줄 고정, 스크롤 활용으로 바꾸었습니다. 
추가로 보이는 형식을 단순 div들 조합에서 table 활용하도록 바꾸었고, 그에 맞춰 세부 css 바꿨습니다.
=> Refactor work detail

frontend/connectoon/src/Containers/WorkDetail/WorkDetail.js, frontend/connectoon/src/Containers/WorkDetail/WorkDetail.test.js, frontend/connectoon/src/store/actions/actionTypes.js, frontend/connectoon/src/store/actions/work.js, frontend/connectoon/src/store/actions/work.test.js, frontend/connectoon/src/store/reducers/work.js, frontend/connectoon/src/store/reducers/work.test.js
add NoSuchWork Case at WorkDetail and corresponding action/reducer, remove reviewNum state from WorkDetail which was for scrolling
=> Scroll을 위한 state 제거, 없는 작품 url 접근 시 예외처리

frontend/connectoon/src/Containers/NavBar/NavBar.css, frontend/connectoon/src/Containers/NavBar/NavBar.js, frontend/connectoon/src/Containers/NavBar/NavBar.test.js
navbar가 원래 창 사이즈를 줄이면 링크랑 버튼끼리 겹치는 문제가 있었는데, 그러지 않도록 css를 수정했습니다. 
또한 회의에서 제기된 링크로 이동 시 dropdown이 사라지지 않는 부분을 수정했습니다.
=> Refactor nav bar

frontend/connectoon/src/Containers/NavBar/NavBar.css, frontend/connectoon/src/Containers/NavBar/NavBar.js
=> Refactor nav bar2

backend/connectoon/work/tests.py, backend/connectoon/work/views.py, frontend/connectoon/src/Components/DetailReview/DetailReview.js, frontend/connectoon/src/Components/DetailReview/DetailReview.test.js, frontend/connectoon/src/Containers/WorkDetail/WorkDetail.js, frontend/connectoon/src/Containers/WorkDetail/WorkDetail.test.js
=> Likes work detail

backend/connectoon/artist/tests.py, backend/connectoon/connectoon/urls.py, backend/connectoon/review/tests.py, backend/connectoon/tag/tests.py, backend/connectoon/user/tests.py, backend/connectoon/work/tests.py, frontend/connectoon/src/index.js
배포 전에 frontend backend url 같은 문제 해결하기 위해 url 수정했습니다.
=> added api/v1/ prefix to url

frontend/connectoon/src/Containers/MyPage/MyPage.css, frontend/connectoon/src/Containers/MyPage/MyPage.js
https://user-images.githubusercontent.com/50933769/145673514-c0399288-4d5e-422e-b396-e38144ed3636.mov
=> Add css to MyPage

frontend/connectoon/src/Containers/NavBar/NavBar.css
https://user-images.githubusercontent.com/50933769/145574182-3e8b342c-88b6-47c0-afcd-94197a6bed69.mov
=> Add css to Navbar

frontend/connectoon/src/Components/BoardReview/BoardReview.js, frontend/connectoon/src/Components/BoardReview/BoardReview.test.js, frontend/connectoon/src/Components/DetailReview/DetailReview.js, frontend/connectoon/src/Components/DetailReview/DetailReview.test.js, frontend/connectoon/src/Containers/Board/Board.js, frontend/connectoon/src/Containers/Board/Board.test.js, frontend/connectoon/src/Containers/WorkDetail/WorkDetail.js, frontend/connectoon/src/Containers/WorkDetail/WorkDetail.test.js
=> fix like bug 

frontend/connectoon/package.json, frontend/connectoon/src/App.css, frontend/connectoon/src/App.js, frontend/connectoon/src/Containers/Register/Register.js, frontend/connectoon/src/Containers/Register/Register.test.js, frontend/connectoon/yarn.lock
=> Add Toast and Fix Register with Toast
